CREATE TABLE IF NOT EXISTS "airtable-clone_base" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "airtable-clone_base_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"created_by" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "airtable-clone_base" ADD CONSTRAINT "airtable-clone_base_created_by_airtable-clone_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."airtable-clone_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "base_created_by_idx" ON "airtable-clone_base" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "base_name_idx" ON "airtable-clone_base" USING btree ("name");